{% set version = "1.2.0" %}

package:
  name: backports-asyncio-runner
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/backports.asyncio.runner/backports_asyncio_runner-{{ version }}.tar.gz
  sha256: a5aa7b2b7d8f8bfcaa2b57313f70792df84e32a2a746f585213373f900b42162

build:
  number: 2
  skip: true  # [py>=311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - hatch-fancy-pypi-readme
    - hatchling
    - pip
    - python
  run:
    - python

test:
  imports: backports.asyncio.runner
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/samypr100/backports.asyncio.runner
  summary: Backport of asyncio.Runner, a context manager that controls event loop life cycle.
  description: |
    Backport of asyncio.Runner from Python 3.11. Runner is a context manager that
    controls the event loop life cycle and runs the provided coroutine.
  license: PSF-2.0
  license_file: LICENSE.md
  license_family: PSF
  doc_url: https://github.com/samypr100/backports.asyncio.runner#readme
  dev_url: https://github.com/samypr100/backports.asyncio.runner

extra:
  recipe-maintainers:
    - bollwyvl
